### ISSUE TITLE
List-users does not support the PowerShell pipeline

### ISSUE THREAD

**Issue by jbrinkman** [DNN-Connect/Dnn-Powershell#3]
The List-users command is currently outputing an array from the cmdlet.  This limits the usefulness of the cmdlet since PowerShell expects cmdlets to output a single record at a time, hence the method name ProcessRecord (singular).  List-users should be modified to loop through the array and process each record independently.  This will allow the cmdlet to be used as part of a pipeline.

For example to output a list of users to a spreadsheet, I should be able to use
`list-users | export-csv -path c:\test\out.csv`

This should create a file that can be opened in excel with a list of all the portal users.

# Repro steps
1. Connect to a DNN 9.2.0 site with use-site
2. Execute `List-Users | Get-Member`

# Expected
1. The TypeName of the returned type should be `Connect.DNN.Powershell.Core.Models.UserModelBase`
2. The properties and methods of UserModelBase should be listed

# Actual
1. The TypeName of the returned type is an array `Connect.DNN.Powershell.Core.Models.UserModelBase[]`
2. The properties and methods of arrays are listed.

**Comment by donker** [comment]
OK, I did not know this. It means that all methods that return a list of stuff will need to be refactored accordingly.
